eco:
    resource: '@EcoBundle/Controller/'
    type: annotation
    prefix: /

#    resource: "@EcoBundle/Resources/config/routing.yml"
#    prefix:   /

app:
    resource: '@EcoBundle/Controller/'
    type: annotation
