eco:
    resource: '@EcoBundle/Controller/'
    type: annotation
    prefix: /
#    resource: "@EcoBundle/Resources/config/routing.yml"
#    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#fos_user_group:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#    prefix: /group
app:
    resource: '@EcoBundle/Controller/'
    type: annotation
