eco_homepage:
    path:     /
    defaults: { _controller: EcoBundle:Default:index }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

#users_index:
#    path: /user/
#    defaults: { _controller: EcoBundle:User:index }