<?php

namespace EcoBundle\Repository;

/**
 * AnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnonceRepository extends \Doctrine\ORM\EntityRepository
{
    public function trier()
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT v from EcoBundle:Annonce v ORDER BY v.prix DESC ");

        return $query->getResult();

    }
}
