<?php

namespace EcoBundle\Repository;

/**
 * AnnoncePanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnoncePanierRepository extends \Doctrine\ORM\EntityRepository
{
}
