<?php

namespace EcoBundle\Repository;

/**
 * CategorieMissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieMissionRepository extends \Doctrine\ORM\EntityRepository
{
}
