<?php

namespace EcoBundle\Repository;

/**
 * CategorieEvtsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieEvtsRepository extends \Doctrine\ORM\EntityRepository
{
}
