<?php

namespace EcoBundle\Repository;

/**
 * CategorieAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
