<?php

namespace EcoBundle\Repository;

/**
 * DemeandeCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemeandeCRepository extends \Doctrine\ORM\EntityRepository
{
}
