<?php

namespace EcoBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{

    public function filterEvts($lieu)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT e from EcoBundle:Evenement e WHERE e.lieu=:lieu ")
            ->setParameter('lieu',$lieu)
           ;
        return $query->getResult();
    }
}
