<?php

namespace EcoBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{

    public function filterEvts($lieu)
    {
        $query=$this->getEntityManager()
            ->createQuery("SELECT e from EcoBundle:Missions e WHERE e.lieu=:lieu ")
            ->setParameter('lieu',$lieu)
           ;
        return $query->getResult();
    }

    public function search($search)
    {
        $session = new Session();
        $builder = $this->createQueryBuilder('e');

        // Disponibilité
        if ($search['lieu'] !== null) {
            $session->set('lieu', $search['lieu']);
        } else {
            $search['lieu'] = $session->get('lieu');
        }
        if ($search['lieu']) {
            $builder->andWhere('e.lieu = :lieu')
                ->setParameter('lieu', $search['lieu']);
        }

//        // Expérience
//        if ($search['experience'] !== null) {
//            $session->set('experience', $search['experience']);
//        } else {
//            $search['experience'] = $session->get('experience');
//        }
//        if ($search['experience']) {
//            $builder->andWhere('p.experience >= :experience')
//                ->setParameter('experience', $search['experience']);
//        }
//
//        // Intéret
//        if ($search['interet'] !== null) {
//            $session->set('interet', $search['interet']);
//        } else {
//            $search['interet'] = $session->get('interet');
//        }
//        if ($search['interet']) {
//            $builder->andWhere('p.interet = :interet')
//                ->setParameter('interet', $search['interet']);
//        }
//
//        /// contrat
//        if ($search['contrat'] !== null) {
//            $session->set('contrat', $search['contrat']);
//        } else {
//            $search['contrat'] = $session->get('contrat');
//        }
//        if ($search['contrat']) {
//            $builder->andWhere('p.contrat = :contrat')
//                ->setParameter('contrat', $search['contrat']);
//        }
//
//        // competence
//        if ($search['competences'] !== null) {
//            $session->set('competences', $search['competences']);
//        } else {
//            $search['competences'] = $session->get('competences');
//        }
//        if ($search['competences']) {
//            $builder->innerJoin('p.competences', 'c', 'WITH', 'c.id = :competences')
//                ->setParameter('competences', $search['competences']);
//        }
//
//        // ambition
//        if ($search['ambition'] !== null) {
//            $session->set('ambition', $search['ambition']);
//        } else {
//            $search['ambition'] = $session->get('ambition');
//        }
//        if ($search['ambition']) {
//            $builder->andWhere('p.ambition = :ambition')
//                ->setParameter('ambition', $search['ambition']);
//        }


        return $builder->orderBy("e.id", 'DESC')->getQuery()->getResult();
    }

    public function searchByLieu($lieu)
    {
        $query=$this->getEntityManager()->createQuery("SELECT m from EcoBundle:Missions m WHERE m.lieu=:lieu")
            ->setParameter('lieu',$lieu);
        return $query->getResult();
    }

    public function searchByCategorieEvt($categorie)
    {
        $query=$this->getEntityManager()->createQuery("SELECT m from EcoBundle:Missions m WHERE m.categorie=:categorie")
            ->setParameter('categorie',$categorie);
        return $query->getResult();
    }
}
