<?php

namespace EcoBundle\Repository;

/**
 * MentionAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MentionAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
