<?php

namespace EcoBundle\Repository;

/**
 * MissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionsRepository extends \Doctrine\ORM\EntityRepository
{

    public function filterEvts($lieu)
    {
        $query=$this->getEntityManager()
                    ->createQuery("SELECT e from EcoBundle:Missions e WHERE e.lieu=:lieu ")
                    ->setParameter('lieu',$lieu)
        ;
        return $query->getResult();
    }

    public function search($search)
    {
        $session = new Session();
        $builder = $this->createQueryBuilder('e');

        // Disponibilité
        if ($search['lieu'] !== null) {
            $session->set('lieu', $search['lieu']);
        } else {
            $search['lieu'] = $session->get('lieu');
        }
        if ($search['lieu']) {
            $builder->andWhere('e.lieu = :lieu')
                    ->setParameter('lieu', $search['lieu']);
        }
        return $builder->orderBy("e.id", 'DESC')->getQuery()->getResult();
    }

    public function searchByLieu($lieu)
    {
        $query=$this->getEntityManager()->createQuery("SELECT m from EcoBundle:Missions m WHERE m.lieu=:lieu")
                    ->setParameter('lieu',$lieu);
        return $query->getResult();
    }

    public function searchByCategorieEvt($categorie)
    {
        $query=$this->getEntityManager()->createQuery("SELECT m from EcoBundle:Missions m WHERE m.categorie=:categorie")
                    ->setParameter('categorie',$categorie);
        return $query->getResult();
    }
}
