<?php

namespace NewslettersBundle\Repository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends \Doctrine\ORM\EntityRepository
{
    public function searchNewslettersBy($words)
    {
        $query = $this->getEntityManager()->createQuery("SELECT a from NewslettersBundle:Newsletter a where a.subject LIKE :words or a.contenu LIKE :words ")
            ->setParameter('words', '%' . $words . '%')
            ->setParameter('words', '%' . $words . '%');

        return $query->getResult();
    }
}
