<?php

namespace EcoBundle\Repository;

/**
 * PtCollecteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PtCollecteRepository extends \Doctrine\ORM\EntityRepository
{
}
