<?php

namespace EcoBundle\Repository;

/**
 * PublicationForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationForumRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPublicationByEtat($etat)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $q  = $qb->select(array('p'))
            ->from('EcoBundle:PublicationForum', 'p')
            ->where('p.etat =:published')
            ->orderBy('p.publicationCreatedAt', 'DESC')
            ->setParameter('published', $etat)
            ->getQuery();
        return $q->getResult();
    }
    public function findPublication($keyWord)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $q  = $qb->select(array('p'))
            ->from('EcoBundle:PublicationForum', 'p')
            ->where('p.titre LIKE :motClee')
            ->orWhere('p.description LIKE :motClee')
            ->orderBy('p.publicationCreatedAt', 'DESC')
            ->setParameter('motClee', '%'.$keyWord.'%')
            ->getQuery();
        return $q->getResult();
    }
}
