<?php

namespace EcoBundle\Repository;

/**
 * PublicationForumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationForumRepository extends \Doctrine\ORM\EntityRepository
{
}
