<?php

namespace EcoBundle\Repository;

/**
 * RespAssociationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespAssociationRepository extends \Doctrine\ORM\EntityRepository
{
}
