<?php

namespace EcoBundle\Repository;

/**
 * RespAssoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespAssoRepository extends \Doctrine\ORM\EntityRepository
{
}
