<?php

namespace EcoBundle\Repository;

/**
 * RespSocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RespSocRepository extends \Doctrine\ORM\EntityRepository
{
}
