<?php

namespace EcoBundle\Repository;

/**
 * SignalAnnonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalAnnonceRepository extends \Doctrine\ORM\EntityRepository
{
}
