<?php

namespace EcoBundle\Repository;

/**
 * SignalisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalisationRepository extends \Doctrine\ORM\EntityRepository
{
}
