<?php

namespace EcoBundle\Repository;

/**
 * SignalAnnounceRepRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalAnnounceRepRepository extends \Doctrine\ORM\EntityRepository
{
}
