<?php

namespace EcoBundle\Repository;

/**
 * SubcribeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcribeRepository extends \Doctrine\ORM\EntityRepository
{

}
